/**
 * ╔══════════════════════════════════════════════════════════════╗
 * ║  LEGEND MOTORS PS — Car Inventory Data                      ║
 * ║                                                              ║
 * ║  HOW TO ADD A NEW CAR:                                       ║
 * ║  1. Copy any car object below                                ║
 * ║  2. Change the id (must be unique, e.g., "car-23")           ║
 * ║  3. Change the slug (URL-friendly, e.g., "2025-toyota-rav4") ║
 * ║  4. Update all fields with the new car's info                ║
 * ║  5. Add photo URLs to the photos array                       ║
 * ║  6. Save this file — the site will auto-update               ║
 * ║                                                              ║
 * ║  HOW TO CONNECT A REAL DATABASE LATER:                       ║
 * ║  Replace the `cars` export with a fetch call to your          ║
 * ║  Supabase / Airtable / API endpoint. The Car type stays      ║
 * ║  the same — just change the data source.                     ║
 * ╚══════════════════════════════════════════════════════════════╝
 */

import { Car, Testimonial } from "./types";

// ─── Real car images from Imagin Studio CDN (free for demos) ───
// These generate actual renders of each car by make, model, year, and angle.
// Replace with your own photos later for production.
const carImg = (make: string, model: string, year: number, angle: number) =>
  `https://cdn.imagin.studio/getimage?customer=hrjavascript-mastery&make=${encodeURIComponent(make)}&modelFamily=${encodeURIComponent(model)}&modelYear=${year}&angle=${angle}&zoomType=fullscreen&width=800`;

// Helper to generate 6 angles for each car
const carPhotos = (make: string, model: string, year: number) => [
  carImg(make, model, year, 1),   // front 3/4 view
  carImg(make, model, year, 9),   // rear 3/4 view
  carImg(make, model, year, 13),  // side view
  carImg(make, model, year, 23),  // front view
  carImg(make, model, year, 29),  // rear view
  carImg(make, model, year, 5),   // alternate angle
];

export const cars: Car[] = [
  {
    id: "car-1",
    slug: "2024-toyota-camry-le",
    title: "2024 Toyota Camry LE",
    make: "Toyota",
    model: "Camry",
    year: 2024,
    price: 28500,
    originalPrice: 31000,
    mileage: 1200,
    bodyType: "Sedan",
    fuel: "Petrol",
    transmission: "Automatic",
    color: "Pearl White",
    condition: "New",
    photos: carPhotos("Toyota", "Camry", 2024),
    description:
      "Brand new 2024 Toyota Camry LE with the latest safety features and a refined interior. This midsize sedan delivers excellent fuel economy and legendary Toyota reliability. Perfect for families and professionals who want comfort without compromise.",
    specs: {
      engine: "2.5L 4-Cylinder",
      horsepower: 203,
      torque: "184 lb-ft",
      fuelEconomy: "28 city / 39 hwy mpg",
      drivetrain: "FWD",
      seating: 5,
      cargo: "15.1 cu ft",
      dimensions: "192.1″ L × 72.4″ W × 56.9″ H",
      weight: "3,310 lbs",
    },
    features: [
      "Toyota Safety Sense 3.0",
      "8\" Touchscreen Display",
      "Apple CarPlay & Android Auto",
      "Adaptive Cruise Control",
      "Lane Departure Alert",
      "Pre-Collision System",
      "Blind Spot Monitor",
      "LED Headlights",
      "Dual-Zone Climate Control",
      "Keyless Entry & Push Start",
    ],
    certified: false,
    warranty: "3 years / 36,000 miles basic warranty",
    addedDate: "2024-12-01",
  },
  {
    id: "car-2",
    slug: "2023-hyundai-tucson-sel",
    title: "2023 Hyundai Tucson SEL",
    make: "Hyundai",
    model: "Tucson",
    year: 2023,
    price: 32000,
    mileage: 8500,
    bodyType: "SUV",
    fuel: "Petrol",
    transmission: "Automatic",
    color: "Phantom Black",
    condition: "Certified Pre-Owned",
    photos: carPhotos("Hyundai", "Tucson", 2023),
    description:
      "This certified pre-owned 2023 Hyundai Tucson SEL combines bold styling with cutting-edge technology. The angular design turns heads while the spacious interior keeps everyone comfortable. AWD capability makes it perfect for all road conditions.",
    specs: {
      engine: "2.5L 4-Cylinder",
      horsepower: 187,
      torque: "178 lb-ft",
      fuelEconomy: "26 city / 33 hwy mpg",
      drivetrain: "AWD",
      seating: 5,
      cargo: "38.7 cu ft",
      dimensions: "182.3″ L × 73.4″ W × 66.1″ H",
      weight: "3,651 lbs",
    },
    features: [
      "10.25\" Touchscreen Navigation",
      "Hyundai SmartSense",
      "Wireless Apple CarPlay",
      "Heated Front Seats",
      "Power Liftgate",
      "360-Degree Camera",
      "Remote Start",
      "Leather Seats",
      "Panoramic Sunroof",
      "Wireless Charging",
    ],
    certified: true,
    warranty: "5 years / 60,000 miles powertrain",
    addedDate: "2024-11-15",
  },
  {
    id: "car-3",
    slug: "2024-kia-sportage-lx",
    title: "2024 Kia Sportage LX",
    make: "Kia",
    model: "Sportage",
    year: 2024,
    price: 30500,
    originalPrice: 33000,
    mileage: 500,
    bodyType: "SUV",
    fuel: "Petrol",
    transmission: "Automatic",
    color: "Gravity Grey",
    condition: "New",
    photos: carPhotos("Kia", "Sportage", 2024),
    description:
      "The all-new 2024 Kia Sportage LX features a stunning boomerang-shaped LED daytime running light design. It offers one of the most spacious interiors in its class with advanced driver assistance technologies. An excellent choice for style-conscious families.",
    specs: {
      engine: "2.5L 4-Cylinder",
      horsepower: 187,
      torque: "178 lb-ft",
      fuelEconomy: "26 city / 32 hwy mpg",
      drivetrain: "FWD",
      seating: 5,
      cargo: "39.6 cu ft",
      dimensions: "183.5″ L × 73.4″ W × 66.1″ H",
      weight: "3,546 lbs",
    },
    features: [
      "8\" Touchscreen",
      "Forward Collision Avoidance",
      "Lane Keep Assist",
      "Driver Attention Warning",
      "Apple CarPlay & Android Auto",
      "Rear Cross-Traffic Alert",
      "Smart Key with Push Start",
      "LED Headlights & Taillights",
    ],
    certified: false,
    warranty: "5 years / 60,000 miles basic warranty",
    addedDate: "2024-12-10",
  },
  {
    id: "car-4",
    slug: "2022-volkswagen-passat-r-line",
    title: "2022 Volkswagen Passat R-Line",
    make: "Volkswagen",
    model: "Passat",
    year: 2022,
    price: 24500,
    mileage: 22000,
    bodyType: "Sedan",
    fuel: "Petrol",
    transmission: "Automatic",
    color: "Reflex Silver",
    condition: "Used",
    photos: carPhotos("Volkswagen", "Passat", 2022),
    description:
      "A refined German sedan with the sporty R-Line package. This Passat delivers a smooth ride with turbocharged performance and a premium interior. German engineering at a great value.",
    specs: {
      engine: "2.0L Turbo 4-Cylinder",
      horsepower: 174,
      torque: "206 lb-ft",
      fuelEconomy: "24 city / 36 hwy mpg",
      drivetrain: "FWD",
      seating: 5,
      cargo: "15.9 cu ft",
      dimensions: "193.6″ L × 72.2″ W × 58.5″ H",
      weight: "3,371 lbs",
    },
    features: [
      "R-Line Exterior Styling",
      "6.3\" Touchscreen",
      "Fender Premium Audio",
      "Adaptive Cruise Control",
      "Blind Spot Monitor",
      "Rear Traffic Alert",
      "Heated Front Seats",
      "Dual-Zone Climate",
      "18\" R-Line Wheels",
    ],
    certified: false,
    warranty: "Remaining factory warranty",
    addedDate: "2024-10-20",
  },
  {
    id: "car-5",
    slug: "2024-toyota-rav4-xle",
    title: "2024 Toyota RAV4 XLE",
    make: "Toyota",
    model: "RAV4",
    year: 2024,
    price: 34000,
    mileage: 800,
    bodyType: "SUV",
    fuel: "Hybrid",
    transmission: "Automatic",
    color: "Blueprint",
    condition: "New",
    photos: carPhotos("Toyota", "RAV4", 2024),
    description:
      "The 2024 Toyota RAV4 XLE Hybrid combines outstanding fuel economy with all-wheel drive capability. This compact SUV is America's best-selling SUV for good reason — it does everything well and looks great doing it.",
    specs: {
      engine: "2.5L Hybrid 4-Cylinder",
      horsepower: 219,
      torque: "163 lb-ft",
      fuelEconomy: "41 city / 38 hwy mpg",
      drivetrain: "AWD",
      seating: 5,
      cargo: "37.5 cu ft",
      dimensions: "180.9″ L × 73.0″ W × 67.0″ H",
      weight: "3,800 lbs",
    },
    features: [
      "Toyota Safety Sense 2.5+",
      "8\" Touchscreen with Navigation",
      "Wireless Charging",
      "Power Moonroof",
      "Blind Spot Monitor",
      "Rear Cross-Traffic Alert",
      "SofTex Seats",
      "Power Liftgate",
      "Multi-Terrain Select",
      "EV Mode",
    ],
    certified: false,
    warranty: "3 years / 36,000 miles + hybrid battery 10yr",
    addedDate: "2024-12-05",
  },
  {
    id: "car-6",
    slug: "2023-honda-civic-sport",
    title: "2023 Honda Civic Sport",
    make: "Honda",
    model: "Civic",
    year: 2023,
    price: 25000,
    mileage: 12000,
    bodyType: "Sedan",
    fuel: "Petrol",
    transmission: "Automatic",
    color: "Rallye Red",
    condition: "Used",
    photos: carPhotos("Honda", "Civic", 2023),
    description:
      "The 11th-generation Honda Civic Sport is a head-turner with its aggressive sport styling and engaging driving dynamics. CVT transmission with sport mode delivers responsive performance while maintaining excellent fuel efficiency.",
    specs: {
      engine: "2.0L 4-Cylinder",
      horsepower: 158,
      torque: "138 lb-ft",
      fuelEconomy: "31 city / 40 hwy mpg",
      drivetrain: "FWD",
      seating: 5,
      cargo: "14.8 cu ft",
      dimensions: "184.0″ L × 70.9″ W × 55.7″ H",
      weight: "2,877 lbs",
    },
    features: [
      "7\" Touchscreen",
      "Apple CarPlay & Android Auto",
      "Honda Sensing Suite",
      "Sport Pedals",
      "18\" Alloy Wheels",
      "LED Headlights",
      "Rear Spoiler",
      "Sport Exhaust",
      "Multi-Angle Rearview Camera",
    ],
    certified: false,
    warranty: "Remaining factory warranty until 2026",
    addedDate: "2024-11-28",
  },
  {
    id: "car-7",
    slug: "2024-hyundai-elantra-n-line",
    title: "2024 Hyundai Elantra N Line",
    make: "Hyundai",
    model: "Elantra",
    year: 2024,
    price: 29500,
    mileage: 3000,
    bodyType: "Sedan",
    fuel: "Petrol",
    transmission: "Automatic",
    color: "Intense Blue",
    condition: "Certified Pre-Owned",
    photos: carPhotos("Hyundai", "Elantra", 2024),
    description:
      "The Elantra N Line brings sporty performance to the compact sedan segment. With a turbocharged engine and sport-tuned suspension, it's the perfect balance between daily comfort and weekend fun.",
    specs: {
      engine: "1.6L Turbo 4-Cylinder",
      horsepower: 201,
      torque: "195 lb-ft",
      fuelEconomy: "28 city / 36 hwy mpg",
      drivetrain: "FWD",
      seating: 5,
      cargo: "14.2 cu ft",
      dimensions: "184.1″ L × 71.9″ W × 55.7″ H",
      weight: "3,036 lbs",
    },
    features: [
      "10.25\" Digital Instrument Cluster",
      "10.25\" Navigation Touchscreen",
      "Bose Premium Audio",
      "N Line Sport Seats",
      "Dual-Clutch Transmission",
      "Sport Exhaust",
      "18\" N Line Wheels",
      "Wireless Charging",
      "SmartSense Safety Suite",
    ],
    certified: true,
    warranty: "5 years / 60,000 miles",
    addedDate: "2024-12-08",
  },
  {
    id: "car-8",
    slug: "2023-ford-explorer-xlt",
    title: "2023 Ford Explorer XLT",
    make: "Ford",
    model: "Explorer",
    year: 2023,
    price: 42000,
    originalPrice: 46000,
    mileage: 15000,
    bodyType: "SUV",
    fuel: "Petrol",
    transmission: "Automatic",
    color: "Oxford White",
    condition: "Certified Pre-Owned",
    photos: carPhotos("Ford", "Explorer", 2023),
    description:
      "The 2023 Ford Explorer XLT is a three-row SUV that excels at family duties while offering surprising driving dynamics. The turbocharged EcoBoost engine provides strong performance, and the spacious third row makes it ideal for large families.",
    specs: {
      engine: "2.3L EcoBoost Turbo",
      horsepower: 300,
      torque: "310 lb-ft",
      fuelEconomy: "21 city / 28 hwy mpg",
      drivetrain: "RWD",
      seating: 7,
      cargo: "87.8 cu ft",
      dimensions: "199.3″ L × 78.9″ W × 69.9″ H",
      weight: "4,345 lbs",
    },
    features: [
      "SYNC 4 with 8\" Touchscreen",
      "Ford Co-Pilot360",
      "Wireless Apple CarPlay",
      "Tri-Zone Climate Control",
      "Power Liftgate",
      "SecuriCode Keyless Entry",
      "B&O Sound System",
      "Heated Steering Wheel",
      "Third-Row Seating",
      "Towing Package (5,300 lbs)",
    ],
    certified: true,
    warranty: "7 years / 100,000 miles powertrain",
    addedDate: "2024-11-10",
  },
  {
    id: "car-9",
    slug: "2022-toyota-corolla-le",
    title: "2022 Toyota Corolla LE",
    make: "Toyota",
    model: "Corolla",
    year: 2022,
    price: 19500,
    mileage: 28000,
    bodyType: "Sedan",
    fuel: "Petrol",
    transmission: "Automatic",
    color: "Classic Silver",
    condition: "Used",
    photos: carPhotos("Toyota", "Corolla", 2022),
    description:
      "The Toyota Corolla is the world's best-selling car for a reason. This 2022 LE model offers exceptional reliability, great fuel economy, and a comfortable ride. A smart investment for budget-conscious buyers.",
    specs: {
      engine: "1.8L 4-Cylinder",
      horsepower: 139,
      torque: "126 lb-ft",
      fuelEconomy: "31 city / 40 hwy mpg",
      drivetrain: "FWD",
      seating: 5,
      cargo: "13.1 cu ft",
      dimensions: "182.3″ L × 70.1″ W × 56.5″ H",
      weight: "2,910 lbs",
    },
    features: [
      "Toyota Safety Sense 2.0",
      "8\" Touchscreen",
      "Apple CarPlay",
      "LED Headlights",
      "Adaptive Cruise Control",
      "Lane Tracing Assist",
      "Pre-Collision System",
      "Automatic Climate Control",
    ],
    certified: false,
    warranty: "Remaining powertrain warranty",
    addedDate: "2024-09-15",
  },
  {
    id: "car-10",
    slug: "2024-kia-seltos-sx",
    title: "2024 Kia Seltos SX",
    make: "Kia",
    model: "Seltos",
    year: 2024,
    price: 31000,
    mileage: 2000,
    bodyType: "SUV",
    fuel: "Petrol",
    transmission: "Automatic",
    color: "Starbright Yellow",
    condition: "New",
    photos: carPhotos("Kia", "Seltos", 2024),
    description:
      "The 2024 Kia Seltos SX Turbo packs premium features into a compact SUV body. With its turbocharged engine, it offers peppy performance while the high-tech interior punches well above its price point.",
    specs: {
      engine: "1.6L Turbo 4-Cylinder",
      horsepower: 195,
      torque: "195 lb-ft",
      fuelEconomy: "25 city / 30 hwy mpg",
      drivetrain: "AWD",
      seating: 5,
      cargo: "26.6 cu ft",
      dimensions: "172.6″ L × 70.9″ W × 64.0″ H",
      weight: "3,329 lbs",
    },
    features: [
      "10.25\" Touchscreen Navigation",
      "Bose Premium Audio",
      "Panoramic Sunroof",
      "LED Headlights & Foglamps",
      "360-Degree Camera",
      "Ventilated Front Seats",
      "Wireless Charging",
      "Smart Key",
      "Rain-Sensing Wipers",
    ],
    certified: false,
    warranty: "5 years / 60,000 miles",
    addedDate: "2024-12-12",
  },
  {
    id: "car-11",
    slug: "2021-volkswagen-tiguan-se",
    title: "2021 Volkswagen Tiguan SE",
    make: "Volkswagen",
    model: "Tiguan",
    year: 2021,
    price: 26000,
    mileage: 35000,
    bodyType: "SUV",
    fuel: "Petrol",
    transmission: "Automatic",
    color: "Deep Black Pearl",
    condition: "Used",
    photos: carPhotos("Volkswagen", "Tiguan", 2021),
    description:
      "The Volkswagen Tiguan SE offers German build quality in a practical compact SUV package. The turbocharged engine delivers confident power while the well-crafted interior feels a class above. Available third-row seating adds versatility.",
    specs: {
      engine: "2.0L Turbo 4-Cylinder",
      horsepower: 184,
      torque: "221 lb-ft",
      fuelEconomy: "22 city / 29 hwy mpg",
      drivetrain: "AWD",
      seating: 7,
      cargo: "73.5 cu ft",
      dimensions: "186.1″ L × 72.4″ W × 66.3″ H",
      weight: "3,858 lbs",
    },
    features: [
      "8\" Touchscreen",
      "Panoramic Sunroof",
      "Leather Seats",
      "Blind Spot Monitor",
      "Rear Traffic Alert",
      "Adaptive Cruise Control",
      "Hands-Free Liftgate",
      "Third-Row Seating",
      "Fender Premium Audio",
    ],
    certified: false,
    warranty: "Extended warranty available",
    addedDate: "2024-10-05",
  },
  {
    id: "car-12",
    slug: "2024-toyota-hilux-sr5",
    title: "2024 Toyota Hilux SR5",
    make: "Toyota",
    model: "Hilux",
    year: 2024,
    price: 38000,
    mileage: 1500,
    bodyType: "Truck",
    fuel: "Diesel",
    transmission: "Automatic",
    color: "Graphite",
    condition: "New",
    photos: carPhotos("Toyota", "Hilux", 2024),
    description:
      "The legendary Toyota Hilux needs no introduction. This SR5 model combines rugged capability with modern comfort. The diesel engine offers incredible torque for towing and off-road work. Built to last in the toughest conditions.",
    specs: {
      engine: "2.8L Turbo Diesel 4-Cylinder",
      horsepower: 204,
      torque: "369 lb-ft",
      fuelEconomy: "28 combined mpg",
      drivetrain: "4WD",
      seating: 5,
      cargo: "Bed: 5.0 ft",
      dimensions: "209.6″ L × 72.8″ W × 70.5″ H",
      weight: "4,740 lbs",
    },
    features: [
      "8\" Touchscreen with Navigation",
      "Toyota Safety Sense",
      "Downhill Assist Control",
      "Rear Differential Lock",
      "LED Daytime Running Lights",
      "Cruise Control",
      "Bedliner",
      "Tow Bar",
      "18\" Alloy Wheels",
      "Automatic Climate Control",
    ],
    certified: false,
    warranty: "3 years / 100,000 km",
    addedDate: "2024-12-15",
  },
  {
    id: "car-13",
    slug: "2023-hyundai-sonata-limited",
    title: "2023 Hyundai Sonata Limited",
    make: "Hyundai",
    model: "Sonata",
    year: 2023,
    price: 33500,
    originalPrice: 36000,
    mileage: 9000,
    bodyType: "Sedan",
    fuel: "Petrol",
    transmission: "Automatic",
    color: "Shimmering Silver",
    condition: "Certified Pre-Owned",
    photos: carPhotos("Hyundai", "Sonata", 2023),
    description:
      "The Sonata Limited is Hyundai's flagship sedan loaded with premium features. The striking coupe-like silhouette hides a spacious interior with top-tier tech. Highway Driving Assist makes long commutes effortless.",
    specs: {
      engine: "1.6L Turbo 4-Cylinder",
      horsepower: 180,
      torque: "195 lb-ft",
      fuelEconomy: "27 city / 36 hwy mpg",
      drivetrain: "FWD",
      seating: 5,
      cargo: "16.0 cu ft",
      dimensions: "192.9″ L × 73.2″ W × 56.9″ H",
      weight: "3,330 lbs",
    },
    features: [
      "12.3\" Digital Instrument Cluster",
      "10.25\" Navigation Touchscreen",
      "Bose 12-Speaker Audio",
      "Nappa Leather Seats",
      "Ventilated Front Seats",
      "Head-Up Display",
      "Surround View Monitor",
      "Highway Driving Assist 2",
      "Wireless Charging",
      "Power Sunroof",
    ],
    certified: true,
    warranty: "5 years / 60,000 miles",
    addedDate: "2024-11-20",
  },
  {
    id: "car-14",
    slug: "2020-honda-cr-v-ex",
    title: "2020 Honda CR-V EX",
    make: "Honda",
    model: "CR-V",
    year: 2020,
    price: 27000,
    mileage: 42000,
    bodyType: "SUV",
    fuel: "Petrol",
    transmission: "Automatic",
    color: "Obsidian Blue Pearl",
    condition: "Used",
    photos: carPhotos("Honda", "CR-V", 2020),
    description:
      "The Honda CR-V EX has been one of America's best-selling SUVs for years. This well-maintained example offers a turbocharged engine, Honda Sensing safety suite, and a practical, spacious interior. A dependable family hauler.",
    specs: {
      engine: "1.5L Turbo 4-Cylinder",
      horsepower: 190,
      torque: "179 lb-ft",
      fuelEconomy: "28 city / 34 hwy mpg",
      drivetrain: "AWD",
      seating: 5,
      cargo: "75.8 cu ft",
      dimensions: "182.1″ L × 73.0″ W × 66.5″ H",
      weight: "3,455 lbs",
    },
    features: [
      "Honda Sensing Suite",
      "7\" Touchscreen",
      "Apple CarPlay & Android Auto",
      "Moonroof",
      "Heated Front Seats",
      "Remote Start",
      "Dual-Zone Climate",
      "Push Button Start",
      "Multi-Angle Rearview Camera",
    ],
    certified: false,
    warranty: "Extended warranty available",
    addedDate: "2024-08-22",
  },
  {
    id: "car-15",
    slug: "2024-kia-forte-gt",
    title: "2024 Kia Forte GT",
    make: "Kia",
    model: "Forte",
    year: 2024,
    price: 26500,
    mileage: 500,
    bodyType: "Sedan",
    fuel: "Petrol",
    transmission: "Automatic",
    color: "Snow White Pearl",
    condition: "New",
    photos: carPhotos("Kia", "Forte", 2024),
    description:
      "The Kia Forte GT is the sportiest variant of Kia's popular compact sedan. A turbocharged engine and 7-speed dual-clutch transmission deliver exhilarating performance. Premium features come standard, making it an incredible value.",
    specs: {
      engine: "1.6L Turbo 4-Cylinder",
      horsepower: 201,
      torque: "195 lb-ft",
      fuelEconomy: "27 city / 35 hwy mpg",
      drivetrain: "FWD",
      seating: 5,
      cargo: "15.3 cu ft",
      dimensions: "182.7″ L × 70.9″ W × 56.5″ H",
      weight: "2,952 lbs",
    },
    features: [
      "10.25\" Touchscreen",
      "GT Sport Seats",
      "7-Speed DCT",
      "Bose Audio",
      "LED Headlights",
      "Wireless Charging",
      "Blind Spot Detection",
      "Smart Cruise Control",
      "Sport Exhaust",
      "18\" GT Wheels",
    ],
    certified: false,
    warranty: "5 years / 60,000 miles",
    addedDate: "2024-12-18",
  },
  {
    id: "car-16",
    slug: "2022-toyota-land-cruiser",
    title: "2022 Toyota Land Cruiser",
    make: "Toyota",
    model: "Land Cruiser",
    year: 2022,
    price: 72000,
    mileage: 18000,
    bodyType: "SUV",
    fuel: "Petrol",
    transmission: "Automatic",
    color: "Midnight Black",
    condition: "Used",
    photos: carPhotos("Toyota", "Land Cruiser", 2022),
    description:
      "The iconic Toyota Land Cruiser — a symbol of prestige and unstoppable capability. This flagship SUV goes anywhere and does everything. The luxurious interior and legendary reliability make it the ultimate adventure vehicle.",
    specs: {
      engine: "3.5L Twin-Turbo V6",
      horsepower: 409,
      torque: "479 lb-ft",
      fuelEconomy: "17 city / 22 hwy mpg",
      drivetrain: "4WD",
      seating: 7,
      cargo: "82.8 cu ft",
      dimensions: "194.9″ L × 78.0″ W × 73.6″ H",
      weight: "5,615 lbs",
    },
    features: [
      "12.3\" Touchscreen",
      "Multi-Terrain Select",
      "Crawl Control",
      "Kinetic Dynamic Suspension",
      "JBL 14-Speaker Audio",
      "Heated & Ventilated Seats",
      "Head-Up Display",
      "360-Degree Camera",
      "Fingerprint ID",
      "Wireless Charging",
      "Premium Leather Interior",
      "Power Third Row",
    ],
    certified: false,
    warranty: "Remaining factory warranty",
    addedDate: "2024-11-01",
  },
  {
    id: "car-17",
    slug: "2023-kia-carnival-sx",
    title: "2023 Kia Carnival SX",
    make: "Kia",
    model: "Carnival",
    year: 2023,
    price: 39500,
    mileage: 12000,
    bodyType: "Van",
    fuel: "Petrol",
    transmission: "Automatic",
    color: "Astra Blue",
    condition: "Certified Pre-Owned",
    photos: carPhotos("Kia", "Carnival", 2023),
    description:
      "The Kia Carnival has redefined what a minivan can be. With SUV-like styling and premium features, this SX model is a luxury people mover. Three rows of comfortable seating and dual sunroofs make every journey special.",
    specs: {
      engine: "3.5L V6",
      horsepower: 290,
      torque: "262 lb-ft",
      fuelEconomy: "19 city / 26 hwy mpg",
      drivetrain: "FWD",
      seating: 8,
      cargo: "145.1 cu ft",
      dimensions: "201.4″ L × 78.1″ W × 68.5″ H",
      weight: "4,541 lbs",
    },
    features: [
      "12.3\" Dual Panoramic Displays",
      "Dual Sunroofs",
      "VIP Lounge Seating",
      "Bose 12-Speaker Audio",
      "Dual Power Sliding Doors",
      "Smart Power Liftgate",
      "360-Degree Camera",
      "Highway Driving Assist",
      "Rear Seat Entertainment",
      "Wireless Charging",
    ],
    certified: true,
    warranty: "5 years / 60,000 miles",
    addedDate: "2024-10-30",
  },
  {
    id: "car-18",
    slug: "2024-hyundai-kona-electric",
    title: "2024 Hyundai Kona Electric",
    make: "Hyundai",
    model: "Kona Electric",
    year: 2024,
    price: 35500,
    mileage: 1000,
    bodyType: "SUV",
    fuel: "Electric",
    transmission: "Automatic",
    color: "Cyber Grey",
    condition: "New",
    photos: carPhotos("Hyundai", "Kona", 2024),
    description:
      "Go electric with the all-new 2024 Hyundai Kona Electric. Redesigned from the ground up, it offers an impressive 261-mile range, fast charging capability, and a futuristic interior. The future of driving has arrived.",
    specs: {
      engine: "Electric Motor",
      horsepower: 201,
      torque: "188 lb-ft",
      fuelEconomy: "261 miles range",
      drivetrain: "FWD",
      seating: 5,
      cargo: "27.2 cu ft",
      dimensions: "171.5″ L × 71.9″ W × 61.0″ H",
      weight: "3,714 lbs",
    },
    features: [
      "12.3\" Dual Display Setup",
      "Vehicle-to-Load (V2L)",
      "800V Ultra-Fast Charging",
      "Ambient Lighting",
      "Digital Key",
      "Over-The-Air Updates",
      "SmartSense Safety Suite",
      "Heated & Ventilated Seats",
      "Regenerative Braking",
      "Eco-Processed Interior",
    ],
    certified: false,
    warranty: "5 years / 60,000 miles + 10yr battery",
    addedDate: "2024-12-20",
  },
  {
    id: "car-19",
    slug: "2021-ford-f150-xlt",
    title: "2021 Ford F-150 XLT",
    make: "Ford",
    model: "F-150",
    year: 2021,
    price: 41000,
    originalPrice: 44000,
    mileage: 30000,
    bodyType: "Truck",
    fuel: "Petrol",
    transmission: "Automatic",
    color: "Iconic Silver",
    condition: "Used",
    photos: carPhotos("Ford", "F-150", 2021),
    description:
      "The Ford F-150 XLT is America's best-selling truck. This capable workhorse features the powerful EcoBoost engine, advanced towing technology, and a military-grade aluminum body. Whether for work or weekend adventures, the F-150 delivers.",
    specs: {
      engine: "2.7L EcoBoost V6",
      horsepower: 325,
      torque: "400 lb-ft",
      fuelEconomy: "20 city / 26 hwy mpg",
      drivetrain: "4WD",
      seating: 6,
      cargo: "Bed: 6.5 ft",
      dimensions: "231.7″ L × 79.9″ W × 75.5″ H",
      weight: "4,705 lbs",
    },
    features: [
      "SYNC 4 with 12\" Touchscreen",
      "Ford Co-Pilot360",
      "Pro Trailer Backup Assist",
      "360-Degree Camera",
      "Spray-In Bedliner",
      "Trailer Tow Package (10,000 lbs)",
      "Running Boards",
      "LED Box Lighting",
      "Remote Start",
      "B&O Premium Audio",
    ],
    certified: false,
    warranty: "Extended warranty available",
    addedDate: "2024-09-10",
  },
  {
    id: "car-20",
    slug: "2023-volkswagen-golf-gti",
    title: "2023 Volkswagen Golf GTI",
    make: "Volkswagen",
    model: "Golf GTI",
    year: 2023,
    price: 32000,
    mileage: 11000,
    bodyType: "Hatchback",
    fuel: "Petrol",
    transmission: "Manual",
    color: "Kings Red",
    condition: "Used",
    photos: carPhotos("Volkswagen", "Golf", 2023),
    description:
      "The Volkswagen Golf GTI is the original hot hatch and still the benchmark. This 8th generation model delivers thrilling performance with everyday practicality. The 6-speed manual gearbox makes every drive engaging.",
    specs: {
      engine: "2.0L Turbo 4-Cylinder",
      horsepower: 241,
      torque: "273 lb-ft",
      fuelEconomy: "25 city / 34 hwy mpg",
      drivetrain: "FWD",
      seating: 5,
      cargo: "19.9 cu ft",
      dimensions: "170.4″ L × 70.6″ W × 58.2″ H",
      weight: "3,150 lbs",
    },
    features: [
      "10.25\" Digital Cockpit Pro",
      "10\" Discover Pro Touchscreen",
      "Harman Kardon Audio",
      "Plaid Sport Seats",
      "6-Speed Manual",
      "Electronic Differential Lock",
      "Adaptive Chassis Control",
      "LED Matrix Headlights",
      "Rear Spoiler",
      "19\" GTI Wheels",
    ],
    certified: false,
    warranty: "Remaining factory warranty",
    addedDate: "2024-11-05",
  },
  {
    id: "car-21",
    slug: "2024-toyota-corolla-cross-hybrid",
    title: "2024 Toyota Corolla Cross Hybrid",
    make: "Toyota",
    model: "Corolla Cross",
    year: 2024,
    price: 30500,
    mileage: 600,
    bodyType: "SUV",
    fuel: "Hybrid",
    transmission: "Automatic",
    color: "Celestite Grey",
    condition: "New",
    photos: carPhotos("Toyota", "Corolla Cross", 2024),
    description:
      "The Corolla Cross Hybrid brings Toyota's legendary hybrid technology to the popular compact crossover segment. With standard AWD and exceptional fuel economy, it's the smart choice for daily commuters who want SUV versatility.",
    specs: {
      engine: "2.0L Hybrid 4-Cylinder",
      horsepower: 194,
      torque: "139 lb-ft",
      fuelEconomy: "42 city / 41 hwy mpg",
      drivetrain: "AWD",
      seating: 5,
      cargo: "26.5 cu ft",
      dimensions: "175.6″ L × 72.4″ W × 64.8″ H",
      weight: "3,380 lbs",
    },
    features: [
      "8\" Touchscreen",
      "Toyota Safety Sense 3.0",
      "Wireless Apple CarPlay",
      "Wireless Charging",
      "Blind Spot Monitor",
      "Rear Cross-Traffic Alert",
      "Power Liftgate",
      "Heated Front Seats",
      "LED Headlights",
    ],
    certified: false,
    warranty: "3 years / 36,000 miles + hybrid battery 10yr",
    addedDate: "2024-12-22",
  },
  {
    id: "car-22",
    slug: "2019-honda-accord-sport",
    title: "2019 Honda Accord Sport",
    make: "Honda",
    model: "Accord",
    year: 2019,
    price: 22000,
    mileage: 48000,
    bodyType: "Sedan",
    fuel: "Petrol",
    transmission: "Automatic",
    color: "Still Night Pearl",
    condition: "Used",
    photos: carPhotos("Honda", "Accord", 2019),
    description:
      "The Honda Accord Sport is a benchmark midsize sedan that balances performance, comfort, and reliability. The turbocharged engine provides spirited acceleration while still delivering great fuel economy. A proven choice at a great price.",
    specs: {
      engine: "1.5L Turbo 4-Cylinder",
      horsepower: 192,
      torque: "192 lb-ft",
      fuelEconomy: "30 city / 38 hwy mpg",
      drivetrain: "FWD",
      seating: 5,
      cargo: "16.7 cu ft",
      dimensions: "192.2″ L × 73.3″ W × 57.1″ H",
      weight: "3,131 lbs",
    },
    features: [
      "8\" Touchscreen",
      "Honda Sensing Suite",
      "Apple CarPlay & Android Auto",
      "19\" Sport Wheels",
      "Sport Pedals",
      "Dual-Zone Climate",
      "LED Headlights",
      "Remote Start",
      "Multi-Angle Camera",
    ],
    certified: false,
    warranty: "Extended warranty available",
    addedDate: "2024-07-18",
  },
];

// ─── Helper to get unique values for filters ───
export const allMakes = [...new Set(cars.map((c) => c.make))].sort();
export const allBodyTypes = [...new Set(cars.map((c) => c.bodyType))].sort();
export const allFuelTypes = [...new Set(cars.map((c) => c.fuel))].sort();
export const allColors = [...new Set(cars.map((c) => c.color))].sort();
export const allConditions = [...new Set(cars.map((c) => c.condition))].sort();

export const modelsByMake: Record<string, string[]> = {};
cars.forEach((c) => {
  if (!modelsByMake[c.make]) modelsByMake[c.make] = [];
  if (!modelsByMake[c.make].includes(c.model)) {
    modelsByMake[c.make].push(c.model);
  }
});

// ─── Testimonials ───
export const testimonials: Testimonial[] = [
  {
    id: 1,
    name: "Ahmad Nasser",
    rating: 5,
    text: "Legend Motors made buying my first car an amazing experience. The team was transparent, the price was fair, and the Camry I got is perfect. Highly recommend!",
    car: "2024 Toyota Camry",
    date: "2024-11-15",
  },
  {
    id: 2,
    name: "Sara Khoury",
    rating: 5,
    text: "I was looking for a reliable SUV for my family. They helped me find the perfect Tucson within my budget. The financing was smooth and fast.",
    car: "2023 Hyundai Tucson",
    date: "2024-10-22",
  },
  {
    id: 3,
    name: "Mohammed Haddad",
    rating: 4,
    text: "Great selection of cars and very professional service. The test drive experience was excellent and they answered all my questions about the warranty.",
    car: "2023 VW Golf GTI",
    date: "2024-09-08",
  },
  {
    id: 4,
    name: "Lina Barakat",
    rating: 5,
    text: "Best dealership in Nablus! I traded in my old car and the process was incredibly smooth. They gave me a fair trade-in value and the new Sportage is amazing.",
    car: "2024 Kia Sportage",
    date: "2024-12-01",
  },
  {
    id: 5,
    name: "Rami Awad",
    rating: 5,
    text: "Third car I've bought from Legend Motors. They're honest, reliable, and always follow up after the sale. My Land Cruiser is a dream come true.",
    car: "2022 Toyota Land Cruiser",
    date: "2024-08-15",
  },
];
